/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.tambo_mysql;

import Resources.CarritoCompras;
import static Resources.CarritoCompras.total_precio;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author Segov
 */
public class Carrito extends javax.swing.JFrame {
    List<String> nombresProductos = CarritoCompras.getNombresProductos();
    List<Integer> cantidadesProductos = CarritoCompras.getCantidadesProductos();
    List<Double> preciosProductos = CarritoCompras.getPreciosProductos();
    List<Double> subtotales = CarritoCompras.getSubtotales();
    
    /**
     * Creates new form Carrito
     */
    public Carrito() {
        initComponents();
        Table_Carrito.requestFocus();
        inicializarLabelDatos();
        Table_Carrito.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table_Carrito = new javax.swing.JTable();
        btnCarrito = new javax.swing.JButton();
        labelTotal = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(176, 18, 129));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Table_Carrito.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Table_Carrito.getTableHeader().setReorderingAllowed(false);
        Table_Carrito.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Table_CarritoFocusGained(evt);
            }
        });
        jScrollPane1.setViewportView(Table_Carrito);
        if (Table_Carrito.getColumnModel().getColumnCount() > 0) {
            Table_Carrito.getColumnModel().getColumn(0).setResizable(false);
            Table_Carrito.getColumnModel().getColumn(1).setResizable(false);
            Table_Carrito.getColumnModel().getColumn(2).setResizable(false);
            Table_Carrito.getColumnModel().getColumn(3).setResizable(false);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        btnCarrito.setText("CATALOGO");
        btnCarrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarritoActionPerformed(evt);
            }
        });
        jPanel1.add(btnCarrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, 100, -1));

        labelTotal.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        labelTotal.setForeground(new java.awt.Color(204, 204, 204));
        labelTotal.setText("00.00");
        jPanel1.add(labelTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 530, 130, 40));

        jButton1.setText("ELIMINAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 90, -1));

        jButton2.setText("PAGAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 490, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarritoActionPerformed
                // Crear una instancia del JFrame "Catalogo"
        Catalogo catalogo = new Catalogo();
        
        // Hacer visible el JFrame "Catalogo"
        catalogo.setVisible(true);
        
        // Ocultar el JFrame actual "Carrito"
        setVisible(false);
    }//GEN-LAST:event_btnCarritoActionPerformed

    private void Table_CarritoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Table_CarritoFocusGained
    // Obtener los datos de las listas de nombres y precios
        
    
    // Crear el modelo de la tabla con las columnas "Producto" y "Precio"
    DefaultTableModel modeloTabla = new DefaultTableModel();
    modeloTabla.addColumn("Producto");
    modeloTabla.addColumn("P. Unit.");
    modeloTabla.addColumn("Cant.");
    modeloTabla.addColumn("Precio");
    
    
    // Agregar filas con los datos de nombres y precios
    for (int i = 0; i < nombresProductos.size(); i++) {
        
        String precioFormateado = String.format("S/. %.2f", preciosProductos.get(i));
        String subtotalFormateado = String.format("S/. %.2f", subtotales.get(i));
        
        
        Object[] fila = {nombresProductos.get(i), precioFormateado, 
                         cantidadesProductos.get(i), subtotalFormateado};
        modeloTabla.addRow(fila);
    }
    
    // Establecer el modelo en la tabla
    Table_Carrito.setModel(modeloTabla);
    
    int[] anchos = {80,50,80};
    
    for (int i = 1; i<=3; i++) {
        TableColumn columna = Table_Carrito.getColumnModel().getColumn(i);
        columna.setMinWidth(anchos[i-1]);
        columna.setMaxWidth(anchos[i-1]);
        columna.setPreferredWidth(anchos[i-1]);
    }

    
// TODO add your handling code here:
    }//GEN-LAST:event_Table_CarritoFocusGained

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int filaSeleccionada = Table_Carrito.getSelectedRow();
        
        if (filaSeleccionada != -1) {
            // Obtener el índice de la fila seleccionada
            int indice = Table_Carrito.convertRowIndexToModel(filaSeleccionada);
            
            // Eliminar el producto de las listas de nombres y precios
            nombresProductos.remove(indice);
            preciosProductos.remove(indice);
            subtotales.remove(indice);
            
            // Actualizar el modelo de la tabla
            DefaultTableModel modeloTabla = (DefaultTableModel) Table_Carrito.getModel();
            modeloTabla.removeRow(indice);
            
            // Limpiar la selección de la tabla
            Table_Carrito.clearSelection();
        }
        inicializarLabelDatos();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        Pago pago = new Pago();
        // Hacer visible el JFrame "Carrito"
        pago.setVisible(true);
        
        // Ocultar el JFrame actual "Catalogo"
        setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Carrito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Carrito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Carrito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Carrito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Carrito().setVisible(true);
            }
        });
    }

public double total() {
    double total = 0.0;
    
    for (double precio : subtotales) {
        total += precio;
    }
    
    return total;
}

    
public String calcularTotal(List<Double> preciosProductos) {
    double total = 0.0;
    
    // Sumar todos los precios
    for (double precio : preciosProductos) {
        total += precio;
    }
    
    // Crear el formato "S/. Total"
    total_precio(total);
    String totalFormateado = String.format("S/. %.2f", total);
    
    return totalFormateado;
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table_Carrito;
    private javax.swing.JButton btnCarrito;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelTotal;
    // End of variables declaration//GEN-END:variables

    private void inicializarLabelDatos() {
        labelTotal.setText(calcularTotal(CarritoCompras.getSubtotales()));
    }
}
