/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.tambo_mysql;

import Resources.ButtonAnimationUtils;
import Resources.TextFieldUtils;
import javax.swing.JTextField;
import Resources.CarritoCompras;

/**
 *
 * @author fabri
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        jLabel1.requestFocusInWindow();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        izquierda = new javax.swing.JPanel();
        jtxtPass = new javax.swing.JPasswordField();
        jbtnIniciarSesion = new javax.swing.JButton();
        jbtnRegistro = new javax.swing.JButton();
        jtxtEmail = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LOGIN");
        setResizable(false);

        izquierda.setBackground(new java.awt.Color(176, 18, 129));
        izquierda.setToolTipText("");
        izquierda.setMinimumSize(new java.awt.Dimension(400, 500));
        izquierda.setPreferredSize(new java.awt.Dimension(400, 500));
        izquierda.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtxtPass.setBackground(new java.awt.Color(176, 18, 129));
        jtxtPass.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jtxtPass.setForeground(new java.awt.Color(204, 204, 204));
        jtxtPass.setText("contraseña__");
        jtxtPass.setToolTipText("contraseña__");
        jtxtPass.setBorder(null);
        jtxtPass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TxtFocusLost(evt);
            }
        });
        jtxtPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtPassActionPerformed(evt);
            }
        });
        izquierda.add(jtxtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 250, 50));

        jbtnIniciarSesion.setBackground(new java.awt.Color(230, 226, 32));
        jbtnIniciarSesion.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jbtnIniciarSesion.setForeground(new java.awt.Color(176, 18, 129));
        jbtnIniciarSesion.setText("INICIAR SESIÓN");
        jbtnIniciarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtnIniciarSesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtnIniciarSesionMouseExited(evt);
            }
        });
        jbtnIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnIniciarSesionActionPerformed(evt);
            }
        });
        izquierda.add(jbtnIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, 240, 40));

        jbtnRegistro.setBackground(new java.awt.Color(230, 226, 32));
        jbtnRegistro.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jbtnRegistro.setForeground(new java.awt.Color(176, 18, 129));
        jbtnRegistro.setText("REGISTRARME");
        jbtnRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtnRegistroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtnRegistroMouseExited(evt);
            }
        });
        jbtnRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRegistroActionPerformed(evt);
            }
        });
        izquierda.add(jbtnRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 470, 240, 40));

        jtxtEmail.setBackground(new java.awt.Color(176, 18, 129));
        jtxtEmail.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jtxtEmail.setForeground(new java.awt.Color(204, 204, 204));
        jtxtEmail.setText("Ingrese su correo");
        jtxtEmail.setToolTipText("Ingrese su correo");
        jtxtEmail.setBorder(null);
        jtxtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TxtFocusLost(evt);
            }
        });
        izquierda.add(jtxtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 250, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/Sprite-0002.png"))); // NOI18N
        izquierda.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        izquierda.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 250, -1));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        izquierda.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 250, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(izquierda, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(izquierda, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void jbtnRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRegistroActionPerformed
        // TODO add your handling code here:

        Registro RegistroFrame = new Registro();
        RegistroFrame.setVisible(true);
        RegistroFrame.pack();
        RegistroFrame.setLocationRelativeTo(null);//Centra el formulario
        this.dispose();
    }//GEN-LAST:event_jbtnRegistroActionPerformed

    private void jbtnIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnIniciarSesionActionPerformed
        // TODO add your handling code here:

        String Email=this.jtxtEmail.getText();
        String Pass=this.jtxtPass.getText();
       
        
        CarritoCompras.setCorreo(jtxtEmail.getText());
    // Crear una instancia de la clase Cliente con los datos ingresados
        Cliente cliente = new Cliente(Email, Pass);

        // Iniciar sesión en la base de datos
        cliente.InicioSeionDB();
                Catalogo catalogo = new Catalogo();
        
        // Hacer visible el JFrame "Catalogo"
        catalogo.setVisible(true);
        
        // Ocultar el JFrame actual "Carrito"
        setVisible(false);

    }//GEN-LAST:event_jbtnIniciarSesionActionPerformed

    private void jtxtPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtPassActionPerformed


    private void jbtnIniciarSesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnIniciarSesionMouseEntered
        jbtnIniciarSesion.setBorderPainted(false);
        jbtnIniciarSesion.setFocusPainted(false);
        ButtonAnimationUtils.animateButtonOnMouseEnter(jbtnIniciarSesion);

    }//GEN-LAST:event_jbtnIniciarSesionMouseEntered

    private void jbtnIniciarSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnIniciarSesionMouseExited
    ButtonAnimationUtils.resetButtonSizeOnMouseExit(jbtnIniciarSesion);    // TODO add your handling code here:
    }//GEN-LAST:event_jbtnIniciarSesionMouseExited

    private void jbtnRegistroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnRegistroMouseEntered
        jbtnRegistro.setBorderPainted(false);
        jbtnRegistro.setFocusPainted(false);
        ButtonAnimationUtils.animateButtonOnMouseEnter(jbtnRegistro);
    }//GEN-LAST:event_jbtnRegistroMouseEntered

    private void jbtnRegistroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnRegistroMouseExited
    ButtonAnimationUtils.resetButtonSizeOnMouseExit(jbtnRegistro);    // TODO add your handling code here:
    }//GEN-LAST:event_jbtnRegistroMouseExited

    private void TxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtFocusGained
        TextFieldUtils.setupClearTextOnFirstClick((JTextField) evt.getSource());
    }//GEN-LAST:event_TxtFocusGained

    private void TxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtFocusLost
        TextFieldUtils.setupClearTextOnFirstClickOff((JTextField) evt.getSource());
    }//GEN-LAST:event_TxtFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel izquierda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton jbtnIniciarSesion;
    private javax.swing.JButton jbtnRegistro;
    private javax.swing.JTextField jtxtEmail;
    private javax.swing.JPasswordField jtxtPass;
    // End of variables declaration//GEN-END:variables
}
